In [1]:
# Import torch

import torch
torch.__version__


'2.5.1+cu121'

In [2]:
# Create random tensor
Tensor = torch.rand(7,7)

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [3]:

# Create another random tensor
anothe_tensor = torch.rand(1,7)
# Perform matrix multiplication
matrix_multiplication = torch.mm(Tensor,anothe_tensor.T)
matrix_multiplication

tensor([[2.5429],
        [2.0551],
        [1.1208],
        [1.7789],
        [1.7520],
        [1.2210],
        [1.4764]])

4. Set the random seed to 0 and do 2 & 3 over again.
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [4]:
# Set manual seed

import random

RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
# Create two random tensors
Tensor = torch.rand(7,7)
anothe_tensor = torch.rand(1,7)
# Matrix multiply tensors
seed_multiplication = torch.mm(Tensor,anothe_tensor.T)
seed_multiplication

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)
   
   If there is, set the GPU random seed to 1234.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(seed=1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:
   
   
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [6]:
# Set random seed

torch.manual_seed(seed=1234)
# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
Tensor = torch.rand(7,7).cuda()
anothe_tensor = torch.rand(1,7).cuda()

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [11]:
# Perform matmul on tensor_A and tensor_B
seed_multiplication = torch.mm(Tensor,anothe_tensor.T)
seed_multiplication

tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
max_value = torch.max(seed_multiplication)
max_value
# Find min
min_value = torch.min(seed_multiplication)
min_value

tensor(1.5166, device='cuda:0')

9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
max_index = torch.argmax(seed_multiplication)
max_index
# Find arg min
min_index = torch.argmin(seed_multiplication)
max_index,min_index


(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

In [15]:
# Set seed

torch.manual_seed(seed=7)
# Create random tensor
random_tensor = torch.rand(1,1,1,10)
# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()
# Print out tensors and their shapes
print(random_tensor,random_tensor.shape)
print(random_tensor_squeezed,random_tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
